# Generated by Django 3.0.3 on 2020-03-03 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='property_pics')),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField(default='0')),
                ('status', models.IntegerField(choices=[(0, 'Rent'), (1, 'Sale')], default=0)),
                ('uniqueness', models.IntegerField(choices=[(0, 'Latest'), (1, 'Offer')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Area')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Category')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
